### ISSUE TITLE
Import returns null.

### ISSUE THREAD

**Issue by alexandretperez** [smart-table/smart-table-vue#1]
When I use `import { table } from 'smart-table-vue'` table is undefined.

When I use `import obj from 'smart-table-vue'` all is imported.

I'm trying to use it with Vue single file components.

    import { table } from 'smart-table-core';
    import { table as tableMixin } from 'smart-table-vue';

    export default {
        mixins: [tableMixin], // <-- Error because tableMixin is undefined.
        created() {
            console.log(tableVue);
        }
    }

Then I tried

    import { table } from 'smart-table-core';
    import all from 'smart-table-vue';

    export default {
        mixins: [all.table], // <-- TypeError: Cannot read property 'onDisplayChange' of undefined
        created() {
            console.log(all.table);
        }
    }

I saw the example in GitHub when you use Vue.component. There's any example using Vue Single File Components?

Source versions:
```
    "vue": "^2.3.3",
    "smart-table-core": "^1.3.5",
    "smart-table-vue": "^0.1.1"
```

**Comment by lorenzofox3** [comment]
Hi, 
smart-table-vue default export is indeed an object whose properties will point to the different mixins. 

the onDisplayChange is a method of an instance of smart-table (which you will likely pass from your root component to the others as "smartTable" property), NOT the mixin. 

so you need to create your smart-table instance in your root component. If you refer to the example provided in this repo (with single file components), please look at the [entry point](https://github.com/smart-table/smart-table-vue/blob/master/example/app.vue#L15). 

Otherwise you can have a look at the simpler [code pen example] (https://codepen.io/lorenzofox3/pen/GmEvLO) to get a better understanding of the boot process
